name: Autodestroy Infra

on:
  issues:
    types: [closed]

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'back')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Destroy
        run: |
          cd terraform
          terraform init
          terraform destroy -auto-approve -var="bucket_name=site-devops-backend"