name: Deploy Backend Infra

on:
  issues:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'back')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.5"

      - name: Deploy Infraestrutura com Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var="bucket_name=site-devops-backend"
          RAW_OUTPUT=$(terraform output api_gateway_url 2>/dev/null | grep -Eo 'https://[^"]+')
          if [[ -z "$RAW_OUTPUT" ]]; then
            echo "❌ ERRO: api_gateway_url não foi encontrado corretamente."
            exit 1
          fi

          printf "API_URL=%s\n" "$RAW_OUTPUT" >> $GITHUB_ENV
          

      - name: Comentar na issue
        run: gh issue comment "$NUMBER" --repo "$REPO" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
          BODY: |
            ✅ Backend serverless provisionado com sucesso!
